version: '2'
services:
  sut:
    build: 
     
      dockerfile: ./dockerfile.test
    links:
      - web 
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
  redis:
    image: redis
